
DROP DATABASE "ecommerce-project-with-spring-boot-and-angular";
--
-- TOC entry 2838 (class 1262 OID 16405)
-- Name: ecommerce-project-with-spring-boot-and-angular; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "ecommerce-project-with-spring-boot-and-angular";

--
-- TOC entry 205 (class 1259 OID 16496)
-- Name: product_category; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.product_category (
    id bigint NOT NULL,
    category_name character varying(255)
    PRIMARY KEY (id)
);

--
-- TOC entry 204 (class 1259 OID 16494)
-- Name: product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- TOC entry 2839 (class 0 OID 0)
-- Dependencies: 204
-- Name: product_category_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.product_category_id_seq OWNED BY public.product_category.id;


--
-- TOC entry 2702 (class 2604 OID 16499)
-- Name: product_category id; Type: DEFAULT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.product_category ALTER COLUMN id SET DEFAULT nextval('public.product_category_id_seq'::regclass);


--
-- TOC entry 2832 (class 0 OID 16496)
-- Dependencies: 205
-- Data for Name: product_category; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO public.product_category VALUES (1, 'Books');
INSERT INTO public.product_category VALUES (2, 'Coffee Mugs');
INSERT INTO public.product_category VALUES (3, 'Mouse Pads');
INSERT INTO public.product_category VALUES (4, 'Luggage Tags');


--
-- TOC entry 203 (class 1259 OID 16485)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.product (
    id bigint NOT NULL,
    active boolean,
    date_created timestamp without time zone,
    description character varying(255),
    image_url character varying(255),
    last_updated timestamp without time zone,
    name character varying(255),
    sku character varying(255),
    unit_price double precision,
    units_in_stock integer,
    product_category_id bigint NOT NULL,
    PRIMARY KEY (id)
);

--
-- TOC entry 202 (class 1259 OID 16483)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- TOC entry 2839 (class 0 OID 0)
-- Dependencies: 202
-- Name: product_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.product_id_seq OWNED BY public.product.id;


--
-- TOC entry 2702 (class 2604 OID 16488)
-- Name: product id; Type: DEFAULT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.product ALTER COLUMN id SET DEFAULT nextval('public.product_id_seq'::regclass);


--
-- TOC entry 2833 (class 0 OID 16485)
-- Dependencies: 203
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product VALUES (25, true, '2023-01-15 20:56:49.056207', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1016.png', NULL, 'Exploring React.js', 'BOOK-TECH-1016', 27.99, 100, 6);
INSERT INTO public.product VALUES (26, true, '2023-01-15 20:56:49.056207', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1017.png', NULL, 'Advanced Techniques in React.js', 'BOOK-TECH-1017', 13.99, 100, 6);
INSERT INTO public.product VALUES (27, true, '2023-01-15 20:56:49.056207', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1018.png', NULL, 'Introduction to C#', 'BOOK-TECH-1018', 26.99, 100, 6);
INSERT INTO public.product VALUES (28, true, '2023-01-15 20:56:49.056207', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1019.png', NULL, 'Crash Course in JavaScript', 'BOOK-TECH-1019', 13.99, 100, 6);
INSERT INTO public.product VALUES (29, true, '2023-01-15 20:56:49.056207', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1020.png', NULL, 'Introduction to Machine Learning', 'BOOK-TECH-1020', 19.99, 100, 6);
INSERT INTO public.product VALUES (30, true, '2023-01-15 20:56:49.056207', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1021.png', NULL, 'Become a Guru in Java', 'BOOK-TECH-1021', 18.99, 100, 6);
INSERT INTO public.product VALUES (31, true, '2023-01-15 20:56:49.056207', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1022.png', NULL, 'Introduction to Python', 'BOOK-TECH-1022', 26.99, 100, 6);
INSERT INTO public.product VALUES (32, true, '2023-01-15 20:56:49.056207', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1023.png', NULL, 'Advanced Techniques in C#', 'BOOK-TECH-1023', 22.99, 100, 6);
INSERT INTO public.product VALUES (33, true, '2023-01-15 20:56:49.056207', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1024.png', NULL, 'The Expert Guide to Machine Learning', 'BOOK-TECH-1024', 16.99, 100, 6);
INSERT INTO public.product VALUES (59, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1000.png', NULL, 'Mouse Pad - Express', 'MOUSEPAD-1000', 17.99, 100, 8);
INSERT INTO public.product VALUES (60, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1001.png', NULL, 'Mouse Pad - Cherokee', 'MOUSEPAD-1001', 17.99, 100, 8);
INSERT INTO public.product VALUES (61, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1002.png', NULL, 'Mouse Pad - Sweeper', 'MOUSEPAD-1002', 17.99, 100, 8);
INSERT INTO public.product VALUES (62, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1003.png', NULL, 'Mouse Pad - Aspire', 'MOUSEPAD-1003', 17.99, 100, 8);
INSERT INTO public.product VALUES (63, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1004.png', NULL, 'Mouse Pad - Dorian', 'MOUSEPAD-1004', 17.99, 100, 8);
INSERT INTO public.product VALUES (64, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1005.png', NULL, 'Mouse Pad - Columbia', 'MOUSEPAD-1005', 17.99, 100, 8);
INSERT INTO public.product VALUES (65, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1006.png', NULL, 'Mouse Pad - Worthing', 'MOUSEPAD-1006', 17.99, 100, 8);
INSERT INTO public.product VALUES (66, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1007.png', NULL, 'Mouse Pad - Oak Cliff', 'MOUSEPAD-1007', 17.99, 100, 8);
INSERT INTO public.product VALUES (67, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1008.png', NULL, 'Mouse Pad - Tachyon', 'MOUSEPAD-1008', 17.99, 100, 8);
INSERT INTO public.product VALUES (68, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1009.png', NULL, 'Mouse Pad - Pan', 'MOUSEPAD-1009', 17.99, 100, 8);
INSERT INTO public.product VALUES (69, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1010.png', NULL, 'Mouse Pad - Phase', 'MOUSEPAD-1010', 17.99, 100, 8);
INSERT INTO public.product VALUES (70, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1011.png', NULL, 'Mouse Pad - Falling', 'MOUSEPAD-1011', 17.99, 100, 8);
INSERT INTO public.product VALUES (71, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1012.png', NULL, 'Mouse Pad - Wispy', 'MOUSEPAD-1012', 17.99, 100, 8);
INSERT INTO public.product VALUES (72, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1013.png', NULL, 'Mouse Pad - Arlington', 'MOUSEPAD-1013', 17.99, 100, 8);
INSERT INTO public.product VALUES (73, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1014.png', NULL, 'Mouse Pad - Gazing', 'MOUSEPAD-1014', 17.99, 100, 8);
INSERT INTO public.product VALUES (74, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1015.png', NULL, 'Mouse Pad - Azura', 'MOUSEPAD-1015', 17.99, 100, 8);
INSERT INTO public.product VALUES (75, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1016.png', NULL, 'Mouse Pad - Quantum Leap', 'MOUSEPAD-1016', 17.99, 100, 8);
INSERT INTO public.product VALUES (76, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1017.png', NULL, 'Mouse Pad - Light Years', 'MOUSEPAD-1017', 17.99, 100, 8);
INSERT INTO public.product VALUES (77, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1018.png', NULL, 'Mouse Pad - Taylor', 'MOUSEPAD-1018', 17.99, 100, 8);
INSERT INTO public.product VALUES (78, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1019.png', NULL, 'Mouse Pad - Gracia', 'MOUSEPAD-1019', 17.99, 100, 8);
INSERT INTO public.product VALUES (79, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1020.png', NULL, 'Mouse Pad - Relax', 'MOUSEPAD-1020', 17.99, 100, 8);
INSERT INTO public.product VALUES (80, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1021.png', NULL, 'Mouse Pad - Windermere', 'MOUSEPAD-1021', 17.99, 100, 8);
INSERT INTO public.product VALUES (81, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1022.png', NULL, 'Mouse Pad - Prancer', 'MOUSEPAD-1022', 17.99, 100, 8);
INSERT INTO public.product VALUES (82, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1023.png', NULL, 'Mouse Pad - Recursion', 'MOUSEPAD-1023', 17.99, 100, 8);
INSERT INTO public.product VALUES (83, true, '2023-01-15 21:04:42.37085', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 'assets/images/products/mousepads/mousepad-luv2code-1024.png', NULL, 'Mouse Pad - Treasure', 'MOUSEPAD-1024', 17.99, 100, 8);
INSERT INTO public.product VALUES (34, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1000.png', NULL, 'Coffee Mug - Express', 'COFFEEMUG-1000', 18.99, 100, 7);
INSERT INTO public.product VALUES (35, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1001.png', NULL, 'Coffee Mug - Cherokee', 'COFFEEMUG-1001', 18.99, 100, 7);
INSERT INTO public.product VALUES (36, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1002.png', NULL, 'Coffee Mug - Sweeper', 'COFFEEMUG-1002', 18.99, 100, 7);
INSERT INTO public.product VALUES (37, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1003.png', NULL, 'Coffee Mug - Aspire', 'COFFEEMUG-1003', 18.99, 100, 7);
INSERT INTO public.product VALUES (38, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1004.png', NULL, 'Coffee Mug - Dorian', 'COFFEEMUG-1004', 18.99, 100, 7);
INSERT INTO public.product VALUES (39, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1005.png', NULL, 'Coffee Mug - Columbia', 'COFFEEMUG-1005', 18.99, 100, 7);
INSERT INTO public.product VALUES (40, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1006.png', NULL, 'Coffee Mug - Worthing', 'COFFEEMUG-1006', 18.99, 100, 7);
INSERT INTO public.product VALUES (41, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1007.png', NULL, 'Coffee Mug - Oak Cliff', 'COFFEEMUG-1007', 18.99, 100, 7);
INSERT INTO public.product VALUES (42, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1008.png', NULL, 'Coffee Mug - Tachyon', 'COFFEEMUG-1008', 18.99, 100, 7);
INSERT INTO public.product VALUES (43, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1009.png', NULL, 'Coffee Mug - Pan', 'COFFEEMUG-1009', 18.99, 100, 7);
INSERT INTO public.product VALUES (44, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1010.png', NULL, 'Coffee Mug - Phase', 'COFFEEMUG-1010', 18.99, 100, 7);
INSERT INTO public.product VALUES (45, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1011.png', NULL, 'Coffee Mug - Falling', 'COFFEEMUG-1011', 18.99, 100, 7);
INSERT INTO public.product VALUES (46, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1012.png', NULL, 'Coffee Mug - Wispy', 'COFFEEMUG-1012', 18.99, 100, 7);
INSERT INTO public.product VALUES (47, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1013.png', NULL, 'Coffee Mug - Arlington', 'COFFEEMUG-1013', 18.99, 100, 7);
INSERT INTO public.product VALUES (48, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1014.png', NULL, 'Coffee Mug - Gazing', 'COFFEEMUG-1014', 18.99, 100, 7);
INSERT INTO public.product VALUES (49, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1015.png', NULL, 'Coffee Mug - Azura', 'COFFEEMUG-1015', 18.99, 100, 7);
INSERT INTO public.product VALUES (50, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1016.png', NULL, 'Coffee Mug - Quantum Leap', 'COFFEEMUG-1016', 18.99, 100, 7);
INSERT INTO public.product VALUES (51, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1017.png', NULL, 'Coffee Mug - Light Years', 'COFFEEMUG-1017', 18.99, 100, 7);
INSERT INTO public.product VALUES (52, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1018.png', NULL, 'Coffee Mug - Taylor', 'COFFEEMUG-1018', 18.99, 100, 7);
INSERT INTO public.product VALUES (53, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1019.png', NULL, 'Coffee Mug - Gracia', 'COFFEEMUG-1019', 18.99, 100, 7);
INSERT INTO public.product VALUES (54, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1020.png', NULL, 'Coffee Mug - Relax', 'COFFEEMUG-1020', 18.99, 100, 7);
INSERT INTO public.product VALUES (55, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1021.png', NULL, 'Coffee Mug - Windermere', 'COFFEEMUG-1021', 18.99, 100, 7);
INSERT INTO public.product VALUES (56, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1022.png', NULL, 'Coffee Mug - Prancer', 'COFFEEMUG-1022', 18.99, 100, 7);
INSERT INTO public.product VALUES (57, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1023.png', NULL, 'Coffee Mug - Recursion', 'COFFEEMUG-1023', 18.99, 100, 7);
INSERT INTO public.product VALUES (58, true, '2023-01-15 21:03:13.848215', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don''t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffeemugs/coffeemug-luv2code-1024.png', NULL, 'Coffee Mug - Treasure', 'COFFEEMUG-1024', 18.99, 100, 7);
INSERT INTO public.product VALUES (9, true, '2023-01-15 20:56:49.056207', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1000.png', NULL, 'Crash Course in Python', 'BOOK-TECH-1000', 14.99, 100, 6);
INSERT INTO public.product VALUES (10, true, '2023-01-15 20:56:49.056207', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1001.png', NULL, 'Become a Guru in JavaScript', 'BOOK-TECH-1001', 20.99, 100, 6);
INSERT INTO public.product VALUES (11, true, '2023-01-15 20:56:49.056207', 'Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1002.png', NULL, 'Exploring Vue.js', 'BOOK-TECH-1002', 14.99, 100, 6);
INSERT INTO public.product VALUES (12, true, '2023-01-15 20:56:49.056207', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1003.png', NULL, 'Advanced Techniques in Big Data', 'BOOK-TECH-1003', 13.99, 100, 6);
INSERT INTO public.product VALUES (13, true, '2023-01-15 20:56:49.056207', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1004.png', NULL, 'Crash Course in Big Data', 'BOOK-TECH-1004', 18.99, 100, 6);
INSERT INTO public.product VALUES (14, true, '2023-01-15 20:56:49.056207', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1005.png', NULL, 'JavaScript Cookbook', 'BOOK-TECH-1005', 23.99, 100, 6);
INSERT INTO public.product VALUES (15, true, '2023-01-15 20:56:49.056207', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1006.png', NULL, 'Beginners Guide to SQL', 'BOOK-TECH-1006', 14.99, 100, 6);
INSERT INTO public.product VALUES (16, true, '2023-01-15 20:56:49.056207', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1007.png', NULL, 'Advanced Techniques in JavaScript', 'BOOK-TECH-1007', 16.99, 100, 6);
INSERT INTO public.product VALUES (17, true, '2023-01-15 20:56:49.056207', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1008.png', NULL, 'Introduction to Spring Boot', 'BOOK-TECH-1008', 25.99, 100, 6);
INSERT INTO public.product VALUES (18, true, '2023-01-15 20:56:49.056207', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1009.png', NULL, 'Become a Guru in React.js', 'BOOK-TECH-1009', 23.99, 100, 6);
INSERT INTO public.product VALUES (19, true, '2023-01-15 20:56:49.056207', 'Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1010.png', NULL, 'Beginners Guide to Data Science', 'BOOK-TECH-1010', 24.99, 100, 6);
INSERT INTO public.product VALUES (20, true, '2023-01-15 20:56:49.056207', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1011.png', NULL, 'Advanced Techniques in Java', 'BOOK-TECH-1011', 19.99, 100, 6);
INSERT INTO public.product VALUES (21, true, '2023-01-15 20:56:49.056207', 'Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1012.png', NULL, 'Exploring DevOps', 'BOOK-TECH-1012', 24.99, 100, 6);
INSERT INTO public.product VALUES (22, true, '2023-01-15 20:56:49.056207', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1013.png', NULL, 'The Expert Guide to SQL', 'BOOK-TECH-1013', 19.99, 100, 6);
INSERT INTO public.product VALUES (23, true, '2023-01-15 20:56:49.056207', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1014.png', NULL, 'Introduction to SQL', 'BOOK-TECH-1014', 22.99, 100, 6);
INSERT INTO public.product VALUES (24, true, '2023-01-15 20:56:49.056207', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/book-luv2code-1015.png', NULL, 'The Expert Guide to JavaScript', 'BOOK-TECH-1015', 22.99, 100, 6);
INSERT INTO public.product VALUES (84, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1000.png', NULL, 'Luggage Tag - Cherish', 'LUGGAGETAG-1000', 16.99, 100, 9);
INSERT INTO public.product VALUES (85, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1001.png', NULL, 'Luggage Tag - Adventure', 'LUGGAGETAG-1001', 16.99, 100, 9);
INSERT INTO public.product VALUES (86, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1002.png', NULL, 'Luggage Tag - Skyline', 'LUGGAGETAG-1002', 16.99, 100, 9);
INSERT INTO public.product VALUES (87, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1003.png', NULL, 'Luggage Tag - River', 'LUGGAGETAG-1003', 16.99, 100, 9);
INSERT INTO public.product VALUES (88, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1004.png', NULL, 'Luggage Tag - Trail Steps', 'LUGGAGETAG-1004', 16.99, 100, 9);
INSERT INTO public.product VALUES (89, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1005.png', NULL, 'Luggage Tag - Blooming', 'LUGGAGETAG-1005', 16.99, 100, 9);
INSERT INTO public.product VALUES (90, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1006.png', NULL, 'Luggage Tag - Park', 'LUGGAGETAG-1006', 16.99, 100, 9);
INSERT INTO public.product VALUES (91, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1007.png', NULL, 'Luggage Tag - Beauty', 'LUGGAGETAG-1007', 16.99, 100, 9);
INSERT INTO public.product VALUES (92, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1008.png', NULL, 'Luggage Tag - Water Fall', 'LUGGAGETAG-1008', 16.99, 100, 9);
INSERT INTO public.product VALUES (93, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1009.png', NULL, 'Luggage Tag - Trail', 'LUGGAGETAG-1009', 16.99, 100, 9);
INSERT INTO public.product VALUES (94, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1010.png', NULL, 'Luggage Tag - Skyscraper', 'LUGGAGETAG-1010', 16.99, 100, 9);
INSERT INTO public.product VALUES (95, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1011.png', NULL, 'Luggage Tag - Leaf', 'LUGGAGETAG-1011', 16.99, 100, 9);
INSERT INTO public.product VALUES (96, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1012.png', NULL, 'Luggage Tag - Jungle', 'LUGGAGETAG-1012', 16.99, 100, 9);
INSERT INTO public.product VALUES (97, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1013.png', NULL, 'Luggage Tag - Shoreline', 'LUGGAGETAG-1013', 16.99, 100, 9);
INSERT INTO public.product VALUES (98, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1014.png', NULL, 'Luggage Tag - Blossom', 'LUGGAGETAG-1014', 16.99, 100, 9);
INSERT INTO public.product VALUES (99, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1015.png', NULL, 'Luggage Tag - Lock', 'LUGGAGETAG-1015', 16.99, 100, 9);
INSERT INTO public.product VALUES (100, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1016.png', NULL, 'Luggage Tag - Cafe', 'LUGGAGETAG-1016', 16.99, 100, 9);
INSERT INTO public.product VALUES (101, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1017.png', NULL, 'Luggage Tag - Darling', 'LUGGAGETAG-1017', 16.99, 100, 9);
INSERT INTO public.product VALUES (102, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1018.png', NULL, 'Luggage Tag - Full Stack', 'LUGGAGETAG-1018', 16.99, 100, 9);
INSERT INTO public.product VALUES (103, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1019.png', NULL, 'Luggage Tag - Courtyard', 'LUGGAGETAG-1019', 16.99, 100, 9);
INSERT INTO public.product VALUES (104, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1020.png', NULL, 'Luggage Tag - Coaster', 'LUGGAGETAG-1020', 16.99, 100, 9);
INSERT INTO public.product VALUES (105, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1021.png', NULL, 'Luggage Tag - Bridge', 'LUGGAGETAG-1021', 16.99, 100, 9);
INSERT INTO public.product VALUES (106, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1022.png', NULL, 'Luggage Tag - Sunset', 'LUGGAGETAG-1022', 16.99, 100, 9);
INSERT INTO public.product VALUES (107, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1023.png', NULL, 'Luggage Tag - Flames', 'LUGGAGETAG-1023', 16.99, 100, 9);
INSERT INTO public.product VALUES (108, true, '2023-01-15 21:12:29.114471', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 'assets/images/products/luggagetags/luggagetag-luv2code-1024.png', NULL, 'Luggage Tag - Countryside', 'LUGGAGETAG-1024', 16.99, 100, 9);

--
-- TOC entry 2705 (class 2606 OID 16502)
-- Name: product fkcwclrqu392y86y0pmyrsi649r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkcwclrqu392y86y0pmyrsi649r FOREIGN KEY (product_category_id) REFERENCES public.product_category(id);